class govImage {
  static Map<String, String> govIme = {
    'Cairo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Cairo.svg/1024px-Flag_of_Cairo.svg.png',
  'Giza': 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Governadorat_de_Gizeh.png',
  'Alexandria':'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Flag_of_Alexandria.svg/1024px-Flag_of_Alexandria.svg.png',
  'Dakahlia':'https://upload.wikimedia.org/wikipedia/commons/f/f2/Governadorat_de_Daqahliya.png',
  'Red Sea':'https://upload.wikimedia.org/wikipedia/commons/7/78/Governadorat_de_la_mar_Roja.png',
  'Beheira':'https://upload.wikimedia.org/wikipedia/commons/7/74/Flag_of_Behira_Govenorate.JPG',
  'Fayoum':'https://upload.wikimedia.org/wikipedia/commons/3/3b/Governadorat_de_Faium.png',
  'Gharbiya':'https://upload.wikimedia.org/wikipedia/commons/b/b0/Governadorat_de_Gharbiya.png',
  'Ismailia':'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Governadorat_d%27Ismailiya.png/1024px-Governadorat_d%27Ismailiya.png',
  'Menofia':'https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Menoufia_Governorate.PNG',
  'Minya':'https://upload.wikimedia.org/wikipedia/commons/3/3e/Flag_of_Minya_Governorate.jpg',
  'Qaliubiya':'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Qalubiya_Governorate.png/1024px-Flag_of_Qalubiya_Governorate.png',
  'New Valley':'https://upload.wikimedia.org/wikipedia/commons/e/ea/Governadorat_de_Wadi_al-Jadid.png',
  'Suez':'https://upload.wikimedia.org/wikipedia/commons/d/da/Governadorat_de_Suez.png',
  'Aswan':'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Governadorat_dAswan.svg/1024px-Governadorat_dAswan.svg.png',
  'Assiut':'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Flag_of_Assiut_Governorate.png/1024px-Flag_of_Assiut_Governorate.png',
  'Beni Suef':'https://upload.wikimedia.org/wikipedia/commons/6/60/Governadorat_de_Bani_Suwayf.png',
  'Port Said':'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Flag_of_Port_Said_Governorate.PNG/1024px-Flag_of_Port_Said_Governorate.PNG',
  'Damietta':'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Flag_of_Damietta_Governorate.svg/1024px-Flag_of_Damietta_Governorate.svg.png',
  'Sharkia':'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_Ash_Sharqiyah.svg/1024px-Flag_of_Ash_Sharqiyah.svg.png',
  'South Sinai':'https://upload.wikimedia.org/wikipedia/commons/4/41/Governadorat_de_Sinai_del_sud.png',
  'Kafr Al sheikh':'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Flag_of_Kafr_El-Sheikh_Governorate_-_01.svg/1024px-Flag_of_Kafr_El-Sheikh_Governorate_-_01.svg.png',
  'Matrouh':'https://upload.wikimedia.org/wikipedia/commons/e/e6/Matrouh_Governorate-logo.PNG',
  'Luxor':'https://upload.wikimedia.org/wikipedia/commons/8/89/Flag_Egy_Luxor.gif',
  'Qena':'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Governadorat_de_Qena_flag.svg/1024px-Governadorat_de_Qena_flag.svg.png',
  'North Sinai':'https://upload.wikimedia.org/wikipedia/commons/0/04/Governadorat_de_Sinai-Sinai_del_nord.png',
  'Sohag':'https://upload.wikimedia.org/wikipedia/commons/1/15/Governadorat_de_Suhaj.png'
  };}
